import type { Metadata } from "next";
import { Space_Grotesk, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Header } from "@/components/ui/header";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${geistMono.variable} antialiased bg-white text-black`}
      >
        {/* Announcement bar */}
        <div className="w-full bg-zinc-900 text-white">
          <div className="mx-auto flex flex-col sm:flex-col lg:flex-row max-w-6xl items-center justify-center px-4 py-2 gap-1 sm:gap-2">
            <div className="text-lg sm:text-lg">
              New season coming! Discount 10%
            </div>
            <div className="flex items-center gap-2 text-lg sm:text-lg">
              for all product! Checkout Now!
              <button className="bg-zinc-700 px-3 py-1 rounded-full text-sm">20:40</button>
            </div>
          </div>
        </div>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
